---
- name: Create root dirs.
  sudo: yes
  file:
    state="directory"
    path="{{item.root}}"
    owner="{{ansible_user_id}}"
    group="www-data"
    mode=0750
  with_items: "{{simp_le_vhosts}}"

- name: Create output dirs.
  sudo: yes
  file:
    state="directory"
    path="{{item.output}}"
    owner="{{ansible_user_id}}"
    group="www-data"
    mode=0750
  with_items: "{{simp_le_vhosts}}"

- name: Copy executable.
  copy:
    src="generate-certs"
    dest="{{simp_le_cache}}/generate-certs"
    mode=0775

- name: Copy configuration.
  template:
    src="conf.json.j2"
    dest="{{simp_le_cache}}/conf.json"

- name: Create certificates.
  command: "'{{simp_le_cache}}/generate-certs' '{{simp_le_cache}}/conf.json'"

- name: Add certificate renewal cron.
  cron:
    name="renew certificates"
    job="'{{simp_le_cache}}/generate-certs' '{{simp_le_cache}}/conf.json'"
    special_time="monthly"

- name: Fix ownerships.
  sudo: yes
  file:
    path="{{item.output}}"
    state="directory"
    owner="{{ansible_user_id}}"
    group="www-data"
    mode="u+rwX,g+rX,o="
    recurse=yes
  with_items: "{{simp_le_vhosts}}"
